#
#all: myElf
#
#myElf: myElf_mine.c
#	gcc -m32 -g -o myElf myElf.c
#
#
#clean:
#	rm -rf myElf

all: myElf_mine

myElf_mine: myElf_mine.c
	gcc -m32 -g -o myElf_mine myElf_mine.c

clean:
	rm -rf myElf_mine